### ISSUE TITLE
Guide to the Human Genome Project

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#11]
Note that in the original page:
http://library.cshl.edu/Guide-to-HGP/

There is graphics, and two buttons linking to resources.

On the integrated website, there is only a single paragraph:
https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/guide-to-the-human-genome-project/

**Comment by srunkows** [comment]
Question: Since this page looked totally different from the rest of the CFH pages, we assumed that this content would not be moved to the core website. Do you want me to move all the content from http://library.cshl.edu/Guide-to-HGP/ to the core  website eliminating the need for the current guide to hgp page?

**Comment by tomadams** [comment]
At the very least there should be a big button to the URL: http://library.cshl.edu/Guide-to-HGP/

Are you able to visually recreate the look of only that page?
(only that page note the libwiki site.)

**Comment by srunkows** [comment]
This is as close as I can get the HGP page reproduced on the core website. Please review: https://lib-review-cshl-core.pantheonsite.io/archives/guide-to-hgp/

**Comment by tomadams** [comment]
You are a coding wizard. Looks great. :star:
