### ISSUE TITLE
Library Homepage - Banner

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#7]
Use full (margin) width banner.
Eliminate "Library" title at top.
Include "Library", over the image banner. Similar to: https://lib-review-cshl-core.pantheonsite.io/research/

**Comment by srunkows** [comment]
I moved the H1 heading below the full width banner image. Please review and let me know if this is better than having the heading above the banner image.

**Comment by tomadams** [comment]
Might want to have the image cropped (remove the bottom 1/3), to free up some space. Don't change it image size, let see if it grows on me.

**Comment by tomadams** [comment]
I do not believe that it is the case anymore that text over an image dings your SEO rankling.

![image](https://user-images.githubusercontent.com/1951133/90133203-10a1bc80-dd3d-11ea-9334-91d20a24fabc.png)

Can we try something like:

https://github.com/tomadams/web2020/blob/8914fe1537ed3215e9b3a0b94a3c84af2f17132d/Library-Hero.html#L1-L37

**Comment by srunkows** [comment]
Thanks Tom. The problem isn't with SEO rankings. Hiding the H1 heading, as you suggested at one point, does hurt SEO rankings. The search engines see it as a manipulation of their algorithms in an attempt to gain rankings for other keywords. The search engines will penalize a website that has hidden text, also known as content cloaking, especially hidden headings, since headings play a major role in their algorithms. It's very hard to recover from this once they penalize the website.

The style of laying heading text over images is not a style we use anywhere else on the website other than on landing page carousels.  This style will not be carried over in the redesign of the carousels. They are being redesigned for a better ADA experience and better experience on mobile devices. Once the new design for the landing page carousels has been rolled out, the H1 heading will be displayed below the carousel. Additionally, the carousel will no longer be full viewport height.

**Comment by tomadams** [comment]
Moving to futures milestone.
