### ISSUE TITLE
Center for Humanities - The Human Genome Project

### ISSUE THREAD

**Issue by tomadams** [tomadams/web2020#72]
On this existing page:
https://lib-review-cshl-core.pantheonsite.io/archives/guide-to-hgp/
please add the following paragraph at the end of "About the HGP" section

The
International History of the Human Genome Project ==> http://genomelegacy.org/
is a related project that CSHL Archives is involved with.

**Comment by srunkows** [comment]
Done and ready for review
https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/guide-to-the-human-genome-project/

**Comment by tomadams** [comment]
I just wanted the https://lib-review-cshl-core.pantheonsite.io/archives/guide-to-hgp/ page updated to add an additional sentence with the link to genomelegacy.org. Please maintain that page with the graphics, links and file attachment.

I did not want a new page created or relocated.

**Comment by srunkows** [comment]
> I just wanted the https://lib-review-cshl-core.pantheonsite.io/archives/guide-to-hgp/ page updated to add an additional sentence with the link to genomelegacy.org. Please maintain that page with the graphics, links and file attachment.
> 
> I did not want a new page created or relocated.

I actually didn't create a new page. https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/guide-to-the-human-genome-project/ already existed. Since the title of this issue is 'Center for Humanities - The Human Genome Project', I assumed you were referring to the page under the Center for Humanities section. I added the sentence to https://lib-review-cshl-core.pantheonsite.io/archives/guide-to-hgp/

Do you want me to delete the guide to hgp page that is in the Center for Humanities section (https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/guide-to-the-human-genome-project/)?

**Comment by tomadams** [comment]
Please delete: https://lib-review-cshl-core.pantheonsite.io/education/center-for-humanities/guide-to-the-human-genome-project/
version.

**Comment by tomadams** [comment]
All is in order. Good.
